import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'or';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation files
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.lessons': 'Lessons',
    'nav.games': 'Games',
    'nav.quiz': 'Quiz',
    'nav.ai': 'AI Chat',
    'nav.notes': 'Notes',
    'nav.profile': 'Profile',
    'nav.notifications': 'Notifications',
    'nav.logout': 'Logout',
    
    // Games Page
    'games.title': 'Physics Games 🎮',
    'games.projectile': '🚀 Projectile Motion',
    'games.formula': '📐 Formula Match',
    'games.dog': '🐕 Dog Physics Adventure',
    'games.gravity': '🌍 Gravity Drop',
    'games.matching': '🎯 Matching Game',
    'games.dragdrop': '🖱️ Drag & Drop',
    
    // Projectile Game
    'projectile.title': '🚀 Projectile Motion',
    'projectile.angle': 'Angle',
    'projectile.speed': 'Speed',
    'projectile.launch': 'Launch',
    'projectile.back': 'Back to Menu',
    
    // Formula Match Game
    'formula.title': 'Formula Match Game',
    'formula.score': 'Score',
    'formula.reset': 'Reset',
    'formula.back': 'Back to Games',
    'formula.instructions': 'Match each physics formula with its correct description!',
    'formula.progress': 'matches found',
    'formula.physics_formulas': 'Physics Formulas',
    'formula.descriptions': 'Descriptions',
    'formula.congratulations': '🎉 Congratulations!',
    'formula.completed': "You've matched all formulas correctly!",
    'formula.final_score': 'Final Score',
    'formula.points': 'points',
    
    // Dog Running Game
    'dog.title': '🐕 Dog Physics Adventure',
    'dog.start': 'Start Game',
    'dog.pause': 'Pause',
    'dog.resume': 'Resume',
    'dog.restart': 'Restart',
    'dog.back': 'Back to Games',
    'dog.controls': 'Controls',
    'dog.movement': 'Movement Controls:',
    'dog.jump': 'Jump',
    'dog.left': 'Switch to Left Track',
    'dog.right': 'Switch to Right Track',
    'dog.slow': 'Slow Down',
    'dog.track_system': 'Track System:',
    'dog.track1': 'Left lane',
    'dog.track2': 'Center lane',
    'dog.track3': 'Right lane',
    'dog.rules': 'Game Rules:',
    'dog.jump_barriers': 'Jump over different height barriers',
    'dog.low_barriers': 'barriers - easy to jump',
    'dog.high_barriers': 'barriers - need perfect timing',
    'dog.green_boxes': 'Green boxes - Physics questions',
    'dog.orange_boxes': 'Orange boxes - Answer options on tracks',
    'dog.choose_track': 'Choose the correct track with the right answer!',
    'dog.wrong_ends': 'Wrong answers end the game',
    'dog.correct_points': 'Correct answers give +10 points',
    'dog.got_it': 'Got it! Start Playing',
    'dog.game_over': 'Game Over! 🐕',
    'dog.final_score': 'Final Score',
    'dog.play_again': 'Play Again',
    'dog.physics_question': '🤔 Physics Question',
    'dog.choose_answer': 'Choose the correct answer to continue running!',
    
    // Gravity Drop Game
    'gravity.title': 'Gravity Drop Simulation',
    'gravity.play': 'Play',
    'gravity.pause': 'Pause',
    'gravity.reset': 'Reset',
    'gravity.back': 'Back to Games',
    'gravity.description': 'Watch how gravity affects a falling object! The ball starts at 100m height.',
    'gravity.height': 'Height',
    'gravity.velocity': 'Velocity',
    'gravity.time': 'Time',
    'gravity.concepts': 'Physics Concepts:',
    'gravity.free_fall': 'Free Fall: Object falling under gravity alone',
    'gravity.acceleration': 'Acceleration: Constant 9.8 m/s² downward',
    'gravity.equations': 'Equations: h = h₀ - ½gt², v = gt',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.finish': 'Finish',
    'common.start': 'Start',
    'common.stop': 'Stop',
    'common.continue': 'Continue',
    'common.retry': 'Retry',
    
    // Language Switcher
    'lang.english': 'English',
    'lang.hindi': 'हिन्दी',
    'lang.odia': 'ଓଡ଼ିଆ',
    'lang.select': 'Select Language',

    // Class Selection
    'class.welcome': 'Welcome to VidyaVerse! 🚀',
    'class.choose': 'Choose your class to start your learning journey',
    'class.subtitle': 'Interactive learning with AI-powered assistance',
    'class.progress': 'Progress',
    'class.enter': 'Enter Class',
    'class.what_get': "What you'll get:",
    'class.ai_tutor': 'AI Tutor',
    'class.mini_games': 'Mini Games',
    'class.xp_badges': 'XP & Badges',
    'class.progress_tracking': 'Progress Tracking',

    // Subject Dashboard
    'subject.back_classes': 'Back to Classes',
    'subject.choose': 'Choose a subject to continue learning',
    'subject.chapters_completed': 'Chapters Completed',
    'subject.xp_earned': 'XP Earned',
    'subject.badges': 'Badges',
    'subject.progress': 'Progress',
    'subject.chapters_available': 'Chapters Available',
    'subject.enter': 'Enter Subject',
    'subject.journey': 'Your Learning Journey',
    'subject.total_xp': 'Total XP',
    'subject.current_level': 'Current Level',
    'subject.streak_days': 'Streak Days',
    'subject.badges_earned': 'Badges Earned',

    // Chapter View
    'chapter.back_subjects': 'Back to Subjects',
    'chapter.back_chapters': 'Back to Chapters',
    'chapter.back_chapter': 'Back to Chapter',
    'chapter.have_fun': 'Have fun while learning!',
    'chapter.study_notes': 'Study Notes',
    'chapter.completed': 'Completed',
    'chapter.quizzes': 'Quizzes',
    'chapter.start_quiz': 'Start Quiz',
    'chapter.mini_games': 'Mini Games',
    'chapter.play_game': 'Play Game',
    'chapter.did_you_know': 'Did You Know? 🤔',
    'chapter.your_progress': 'Your Progress',
    'chapter.notes_read': 'Notes Read',
    'chapter.quizzes_completed': 'Quizzes Completed',
    'chapter.games_played': 'Games Played',
    'chapter.welcome_to': 'Welcome to',
    'chapter.lets_start': "Let's Start! 🚀",
    'chapter.choose_chapter': 'Choose a chapter to start learning',
    'chapter.chapter': 'Chapter',
    'chapter.level': 'Level',
    
    // Lessons Page
    'lessons.title': 'Interactive Physics Lessons 🎯',
    'lessons.subtitle': 'Learn physics through hands-on animations and simulations',
    'lessons.motion_animation': 'Motion Animation',
    'lessons.free_fall': 'Free Fall Motion',
    'lessons.projectile': 'Projectile Motion',
    'lessons.uniform': 'Uniform Motion',
    'lessons.play': 'Play',
    'lessons.pause': 'Pause',
    'lessons.reset': 'Reset',
    'lessons.theory': 'Theory',
    'lessons.key_eq': 'Key Equations:',
    'lessons.mark_complete': '✅ Mark as Complete',
    'lessons.completed_toast': 'Lesson completed! Great job!'
    ,
    // Dashboard
    'dashboard.welcome_back': 'Welcome back',
    'dashboard.subtitle': 'Continue your physics journey with interactive learning',
    'dashboard.lessons_completed': 'Lessons Completed',
    'dashboard.progress': 'Progress',
    'dashboard.average_score': 'Average Score',
    'dashboard.quiz_performance': 'Quiz Performance',
    'dashboard.quizzes_taken': 'Quizzes Taken',
    'dashboard.achievements': 'Achievements',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.start_learning': 'Start Learning',
    'dashboard.choose_class_subject': 'Choose Your Class & Subject',
    'dashboard.continue_learning': 'Continue Learning',
    'dashboard.interactive_lessons': 'Interactive Physics Lessons',
    'dashboard.take_quiz': 'Take Quiz',
    'dashboard.test_knowledge': 'Test Your Knowledge'
    ,
    // Quiz Page
    'quiz.title': 'Physics Quiz 🧠',
    'quiz.subtitle': 'Test your physics knowledge with interactive questions',
    'quiz.question_of': 'Question',
    'quiz.of': 'of',
    'quiz.topic': 'Topic',
    'quiz.previous': 'Previous',
    'quiz.next': 'Next',
    'quiz.submit': 'Submit Quiz 🚀',
    'quiz.complete': 'Quiz Complete!',
    'quiz.your_score': 'Your Score',
    'quiz.your_answer': 'Your answer',
    'quiz.correct': 'Correct',
    'quiz.take_another': 'Take Another Quiz',
    'quiz.completed_toast': 'Quiz completed! You scored'
    ,
    // Teacher
    'teacher.title': 'Teacher Dashboard',
    'teacher.welcome': 'Welcome back',
    'teacher.total_students': 'Total Students',
    'teacher.avg_progress': 'Avg Progress',
    'teacher.lessons': 'Lessons',
    'teacher.avg_score': 'Avg Score',
    'teacher.assignments': 'Assignments',
    'teacher.active': 'Active',
    'teacher.recent_activity': 'Recent Student Activity',
    'teacher.completed_lessons': 'lessons completed',
    'teacher.quick_actions': 'Quick Actions',
    'teacher.create_quiz': 'Create Quiz',
    'teacher.view_students': 'View Students',
    'teacher.attendance': 'Attendance',
    'teacher.add_by_roll': 'Add student by Roll / Enrollment',
    'teacher.enter_roll': 'Enter roll number',
    'teacher.adding': 'Adding...',
    'teacher.add_student': 'Add Student',
    'teacher.toast_not_found': 'No student found with that roll number',
    'teacher.toast_added': 'Student added to your list',
    'teacher.toast_failed': 'Failed to fetch student by roll number'
  },
  
  hi: {
    // Navigation
    'nav.dashboard': 'डैशबोर्ड',
    'nav.lessons': 'पाठ',
    'nav.games': 'खेल',
    'nav.quiz': 'क्विज़',
    'nav.ai': 'AI चैट',
    'nav.notes': 'नोट्स',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.notifications': 'सूचनाएं',
    'nav.logout': 'लॉगआउट',
    
    // Games Page
    'games.title': 'भौतिकी खेल 🎮',
    'games.projectile': '🚀 प्रक्षेप्य गति',
    'games.formula': '📐 सूत्र मैच',
    'games.dog': '🐕 कुत्ता भौतिकी रोमांच',
    'games.gravity': '🌍 गुरुत्वाकर्षण ड्रॉप',
    'games.matching': '🎯 मैचिंग गेम',
    'games.dragdrop': '🖱️ ड्रैग एंड ड्रॉप',
    
    // Projectile Game
    'projectile.title': '🚀 प्रक्षेप्य गति',
    'projectile.angle': 'कोण',
    'projectile.speed': 'गति',
    'projectile.launch': 'लॉन्च करें',
    'projectile.back': 'मेनू पर वापस जाएं',
    
    // Formula Match Game
    'formula.title': 'सूत्र मैच गेम',
    'formula.score': 'स्कोर',
    'formula.reset': 'रीसेट',
    'formula.back': 'खेलों पर वापस जाएं',
    'formula.instructions': 'प्रत्येक भौतिकी सूत्र को उसके सही विवरण के साथ मैच करें!',
    'formula.progress': 'मैच मिले',
    'formula.physics_formulas': 'भौतिकी सूत्र',
    'formula.descriptions': 'विवरण',
    'formula.congratulations': '🎉 बधाई हो!',
    'formula.completed': 'आपने सभी सूत्रों को सही तरीके से मैच किया है!',
    'formula.final_score': 'अंतिम स्कोर',
    'formula.points': 'अंक',
    
    // Dog Running Game
    'dog.title': '🐕 कुत्ता भौतिकी रोमांच',
    'dog.start': 'खेल शुरू करें',
    'dog.pause': 'रोकें',
    'dog.resume': 'जारी रखें',
    'dog.restart': 'पुनः आरंभ',
    'dog.back': 'खेलों पर वापस जाएं',
    'dog.controls': 'नियंत्रण',
    'dog.movement': 'गति नियंत्रण:',
    'dog.jump': 'कूदें',
    'dog.left': 'बाएं ट्रैक पर जाएं',
    'dog.right': 'दाएं ट्रैक पर जाएं',
    'dog.slow': 'धीमा करें',
    'dog.track_system': 'ट्रैक सिस्टम:',
    'dog.track1': 'बायां लेन',
    'dog.track2': 'केंद्र लेन',
    'dog.track3': 'दायां लेन',
    'dog.rules': 'खेल नियम:',
    'dog.jump_barriers': 'विभिन्न ऊंचाई की बाधाओं पर कूदें',
    'dog.low_barriers': 'बाधाएं - कूदना आसान',
    'dog.high_barriers': 'बाधाएं - सही समय की जरूरत',
    'dog.green_boxes': 'हरे बॉक्स - भौतिकी प्रश्न',
    'dog.orange_boxes': 'नारंगी बॉक्स - ट्रैक पर उत्तर विकल्प',
    'dog.choose_track': 'सही उत्तर के साथ सही ट्रैक चुनें!',
    'dog.wrong_ends': 'गलत उत्तर खेल समाप्त करते हैं',
    'dog.correct_points': 'सही उत्तर +10 अंक देते हैं',
    'dog.got_it': 'समझ गया! खेलना शुरू करें',
    'dog.game_over': 'खेल समाप्त! 🐕',
    'dog.final_score': 'अंतिम स्कोर',
    'dog.play_again': 'फिर से खेलें',
    'dog.physics_question': '🤔 भौतिकी प्रश्न',
    'dog.choose_answer': 'दौड़ना जारी रखने के लिए सही उत्तर चुनें!',
    
    // Gravity Drop Game
    'gravity.title': 'गुरुत्वाकर्षण ड्रॉप सिमुलेशन',
    'gravity.play': 'चलाएं',
    'gravity.pause': 'रोकें',
    'gravity.reset': 'रीसेट',
    'gravity.back': 'खेलों पर वापस जाएं',
    'gravity.description': 'देखें कि गुरुत्वाकर्षण गिरते हुए वस्तु को कैसे प्रभावित करता है! गेंद 100m ऊंचाई से शुरू होती है।',
    'gravity.height': 'ऊंचाई',
    'gravity.velocity': 'वेग',
    'gravity.time': 'समय',
    'gravity.concepts': 'भौतिकी अवधारणाएं:',
    'gravity.free_fall': 'मुक्त पतन: केवल गुरुत्वाकर्षण के तहत गिरने वाली वस्तु',
    'gravity.acceleration': 'त्वरण: निरंतर 9.8 m/s² नीचे की ओर',
    'gravity.equations': 'समीकरण: h = h₀ - ½gt², v = gt',
    
    // Common
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.cancel': 'रद्द करें',
    'common.save': 'सहेजें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.close': 'बंद करें',
    'common.back': 'वापस',
    'common.next': 'अगला',
    'common.previous': 'पिछला',
    'common.finish': 'समाप्त करें',
    'common.start': 'शुरू करें',
    'common.stop': 'रोकें',
    'common.continue': 'जारी रखें',
    'common.retry': 'पुनः प्रयास करें',
    
    // Language Switcher
    'lang.english': 'English',
    'lang.hindi': 'हिन्दी',
    'lang.odia': 'ଓଡ଼ିଆ',
    'lang.select': 'भाषा चुनें',

    // Class Selection
    'class.welcome': 'विद्यावर्स में आपका स्वागत है! 🚀',
    'class.choose': 'अपनी सीखने की यात्रा शुरू करने के लिए अपनी कक्षा चुनें',
    'class.subtitle': 'AI-संचालित सहायता के साथ इंटरैक्टिव लर्निंग',
    'class.progress': 'प्रगति',
    'class.enter': 'कक्षा में प्रवेश करें',
    'class.what_get': 'आपको क्या मिलेगा:',
    'class.ai_tutor': 'AI ट्यूटर',
    'class.mini_games': 'मिनी गेम्स',
    'class.xp_badges': 'XP और बैज',
    'class.progress_tracking': 'प्रगति ट्रैकिंग',

    // Subject Dashboard
    'subject.back_classes': 'कक्षाओं पर वापस जाएं',
    'subject.choose': 'सीखना जारी रखने के लिए एक विषय चुनें',
    'subject.chapters_completed': 'अध्याय पूरे',
    'subject.xp_earned': 'प्राप्त XP',
    'subject.badges': 'बैज',
    'subject.progress': 'प्रगति',
    'subject.chapters_available': 'उपलब्ध अध्याय',
    'subject.enter': 'विषय में प्रवेश करें',
    'subject.journey': 'आपकी सीखने की यात्रा',
    'subject.total_xp': 'कुल XP',
    'subject.current_level': 'वर्तमान स्तर',
    'subject.streak_days': 'स्ट्रिक दिन',
    'subject.badges_earned': 'प्राप्त बैज',

    // Chapter View
    'chapter.back_subjects': 'विषयों पर वापस जाएं',
    'chapter.back_chapters': 'अध्यायों पर वापस जाएं',
    'chapter.back_chapter': 'अध्याय पर वापस जाएं',
    'chapter.have_fun': 'सीखते समय मज़ा करें!',
    'chapter.study_notes': 'अध्ययन नोट्स',
    'chapter.completed': 'पूर्ण',
    'chapter.quizzes': 'क्विज़',
    'chapter.start_quiz': 'क्विज़ शुरू करें',
    'chapter.mini_games': 'मिनी गेम्स',
    'chapter.play_game': 'गेम खेलें',
    'chapter.did_you_know': 'क्या आप जानते हैं? 🤔',
    'chapter.your_progress': 'आपकी प्रगति',
    'chapter.notes_read': 'पढ़े गए नोट्स',
    'chapter.quizzes_completed': 'पूरे किए गए क्विज़',
    'chapter.games_played': 'खेले गए गेम्स',
    'chapter.welcome_to': 'स्वागत है',
    'chapter.lets_start': 'चलो शुरू करें! 🚀',
    'chapter.choose_chapter': 'सीखना शुरू करने के लिए अध्याय चुनें',
    'chapter.chapter': 'अध्याय',
    'chapter.level': 'स्तर',

    // Lessons Page
    'lessons.title': 'इंटरैक्टिव भौतिकी पाठ 🎯',
    'lessons.subtitle': 'हाथों-हाथ एनीमेशन और सिमुलेशन के माध्यम से भौतिकी सीखें',
    'lessons.motion_animation': 'मोषन एनीमेशन',
    'lessons.free_fall': 'मुक्त पतन गति',
    'lessons.projectile': 'प्रक्षेप्य गति',
    'lessons.uniform': 'समान गति',
    'lessons.play': 'चलाएं',
    'lessons.pause': 'रोकें',
    'lessons.reset': 'रीसेट',
    'lessons.theory': 'सिद्धांत',
    'lessons.key_eq': 'मुख्य समीकरण:',
    'lessons.mark_complete': '✅ पूर्ण के रूप में चिह्नित करें',
    'lessons.completed_toast': 'पाठ पूरा हुआ! बहुत बढ़िया!'
    ,
    // Dashboard
    'dashboard.welcome_back': 'वापसी पर स्वागत है',
    'dashboard.subtitle': 'इंटरैक्टिव लर्निंग के साथ अपनी भौतिकी यात्रा जारी रखें',
    'dashboard.lessons_completed': 'पूरे किए गए पाठ',
    'dashboard.progress': 'प्रगति',
    'dashboard.average_score': 'औसत स्कोर',
    'dashboard.quiz_performance': 'क्विज़ प्रदर्शन',
    'dashboard.quizzes_taken': 'दिए गए क्विज़',
    'dashboard.achievements': 'उपलब्धियां',
    'dashboard.quick_actions': 'त्वरित क्रियाएं',
    'dashboard.start_learning': 'सीखना शुरू करें',
    'dashboard.choose_class_subject': 'अपनी कक्षा और विषय चुनें',
    'dashboard.continue_learning': 'सीखना जारी रखें',
    'dashboard.interactive_lessons': 'इंटरेक्टिव भौतिकी पाठ',
    'dashboard.take_quiz': 'क्विज़ दें',
    'dashboard.test_knowledge': 'अपना ज्ञान परखें'
    ,
    // Quiz Page
    'quiz.title': 'भौतिकी क्विज़ 🧠',
    'quiz.subtitle': 'इंटरैक्टिव प्रश्नों के साथ अपना ज्ञान परखें',
    'quiz.question_of': 'प्रश्न',
    'quiz.of': 'में से',
    'quiz.topic': 'विषय',
    'quiz.previous': 'पिछला',
    'quiz.next': 'अगला',
    'quiz.submit': 'क्विज़ सबमिट करें 🚀',
    'quiz.complete': 'क्विज़ पूरा!',
    'quiz.your_score': 'आपका स्कोर',
    'quiz.your_answer': 'आपका उत्तर',
    'quiz.correct': 'सही',
    'quiz.take_another': 'एक और क्विज़ लें',
    'quiz.completed_toast': 'क्विज़ पूरा! आपका स्कोर'
    ,
    // Teacher
    'teacher.title': 'शिक्षक डैशबोर्ड',
    'teacher.welcome': 'वापसी पर स्वागत है',
    'teacher.total_students': 'कुल छात्र',
    'teacher.avg_progress': 'औसत प्रगति',
    'teacher.lessons': 'पाठ',
    'teacher.avg_score': 'औसत स्कोर',
    'teacher.assignments': 'असाइनमेंट',
    'teacher.active': 'सक्रिय',
    'teacher.recent_activity': 'हाल की छात्र गतिविधि',
    'teacher.completed_lessons': 'पाठ पूरे',
    'teacher.quick_actions': 'त्वरित क्रियाएं',
    'teacher.create_quiz': 'क्विज़ बनाएं',
    'teacher.view_students': 'छात्र देखें',
    'teacher.attendance': 'उपस्थिति',
    'teacher.add_by_roll': 'रोल/एनरोलमेंट से छात्र जोड़ें',
    'teacher.enter_roll': 'रोल नंबर दर्ज करें',
    'teacher.adding': 'जोड़ रहे हैं...',
    'teacher.add_student': 'छात्र जोड़ें',
    'teacher.toast_not_found': 'उस रोल नंबर के साथ कोई छात्र नहीं मिला',
    'teacher.toast_added': 'छात्र को आपकी सूची में जोड़ा गया',
    'teacher.toast_failed': 'रोल नंबर द्वारा छात्र प्राप्त करने में विफल'
  },
  
  or: {
    // Navigation
    'nav.dashboard': 'ଡ୍ୟାସବୋର୍ଡ',
    'nav.lessons': 'ପାଠ',
    'nav.games': 'ଖେଳ',
    'nav.quiz': 'କ୍ୱିଜ୍',
    'nav.ai': 'AI ଚାଟ',
    'nav.notes': 'ନୋଟ୍',
    'nav.profile': 'ପ୍ରୋଫାଇଲ୍',
    'nav.notifications': 'ବିଜ୍ଞପ୍ତି',
    'nav.logout': 'ଲଗଆଉଟ୍',
    
    // Games Page
    'games.title': 'ଭୌତିକ ବିଜ୍ଞାନ ଖେଳ 🎮',
    'games.projectile': '🚀 ପ୍ରକ୍ଷେପ୍ୟ ଗତି',
    'games.formula': '📐 ସୂତ୍ର ମ୍ୟାଚ୍',
    'games.dog': '🐕 କୁକୁର ଭୌତିକ ବିଜ୍ଞାନ ରୋମାଞ୍ଚ',
    'games.gravity': '🌍 ମାଧ୍ୟାକର୍ଷଣ ଡ୍ରପ୍',
    'games.matching': '🎯 ମ୍ୟାଚିଂ ଗେମ୍',
    'games.dragdrop': '🖱️ ଡ୍ରାଗ୍ ଏଣ୍ଡ୍ ଡ୍ରପ୍',
    
    // Projectile Game
    'projectile.title': '🚀 ପ୍ରକ୍ଷେପ୍ୟ ଗତି',
    'projectile.angle': 'କୋଣ',
    'projectile.speed': 'ଗତି',
    'projectile.launch': 'ଲଞ୍ଚ୍ କରନ୍ତୁ',
    'projectile.back': 'ମେନୁକୁ ଫେରନ୍ତୁ',
    
    // Formula Match Game
    'formula.title': 'ସୂତ୍ର ମ୍ୟାଚ୍ ଗେମ୍',
    'formula.score': 'ସ୍କୋର୍',
    'formula.reset': 'ରିସେଟ୍',
    'formula.back': 'ଖେଳଗୁଡ଼ିକୁ ଫେରନ୍ତୁ',
    'formula.instructions': 'ପ୍ରତ୍ୟେକ ଭୌତିକ ବିଜ୍ଞାନ ସୂତ୍ରକୁ ଏହାର ସଠିକ୍ ବର୍ଣ୍ଣନା ସହିତ ମ୍ୟାଚ୍ କରନ୍ତୁ!',
    'formula.progress': 'ମ୍ୟାଚ୍ ମିଳିଲା',
    'formula.physics_formulas': 'ଭୌତିକ ବିଜ୍ଞାନ ସୂତ୍ର',
    'formula.descriptions': 'ବର୍ଣ୍ଣନା',
    'formula.congratulations': '🎉 ଅଭିନନ୍ଦନ!',
    'formula.completed': 'ଆପଣ ସମସ୍ତ ସୂତ୍ରଗୁଡ଼ିକୁ ସଠିକ୍ ଭାବରେ ମ୍ୟାଚ୍ କରିଛନ୍ତି!',
    'formula.final_score': 'ଅନ୍ତିମ ସ୍କୋର୍',
    'formula.points': 'ପଏଣ୍ଟ୍',
    
    // Dog Running Game
    'dog.title': '🐕 କୁକୁର ଭୌତିକ ବିଜ୍ଞାନ ରୋମାଞ୍ଚ',
    'dog.start': 'ଖେଳ ଆରମ୍ଭ କରନ୍ତୁ',
    'dog.pause': 'ବିରତ',
    'dog.resume': 'ଜାରି ରଖନ୍ତୁ',
    'dog.restart': 'ପୁନଃଆରମ୍ଭ',
    'dog.back': 'ଖେଳଗୁଡ଼ିକୁ ଫେରନ୍ତୁ',
    'dog.controls': 'ନିୟନ୍ତ୍ରଣ',
    'dog.movement': 'ଗତି ନିୟନ୍ତ୍ରଣ:',
    'dog.jump': 'ଡେଇଁବା',
    'dog.left': 'ବାମ ଟ୍ରାକ୍ କୁ ଯାନ୍ତୁ',
    'dog.right': 'ଡାହାଣ ଟ୍ରାକ୍ କୁ ଯାନ୍ତୁ',
    'dog.slow': 'ଧୀର କରନ୍ତୁ',
    'dog.track_system': 'ଟ୍ରାକ୍ ସିଷ୍ଟମ୍:',
    'dog.track1': 'ବାମ ଲେନ୍',
    'dog.track2': 'କେନ୍ଦ୍ର ଲେନ୍',
    'dog.track3': 'ଡାହାଣ ଲେନ୍',
    'dog.rules': 'ଖେଳ ନିୟମ:',
    'dog.jump_barriers': 'ବିଭିନ୍ନ ଉଚ୍ଚତାର ବାଧା ଉପରେ ଡେଇଁବା',
    'dog.low_barriers': 'ବାଧା - ଡେଇଁବା ସହଜ',
    'dog.high_barriers': 'ବାଧା - ସଠିକ୍ ସମୟ ଦରକାର',
    'dog.green_boxes': 'ସବୁଜ ବାକ୍ସ - ଭୌତିକ ବିଜ୍ଞାନ ପ୍ରଶ୍ନ',
    'dog.orange_boxes': 'କମଳା ବାକ୍ସ - ଟ୍ରାକ୍ ଉପରେ ଉତ୍ତର ବିକଳ୍ପ',
    'dog.choose_track': 'ସଠିକ୍ ଉତ୍ତର ସହିତ ସଠିକ୍ ଟ୍ରାକ୍ ବାଛନ୍ତୁ!',
    'dog.wrong_ends': 'ଭୁଲ୍ ଉତ୍ତର ଖେଳ ଶେଷ କରେ',
    'dog.correct_points': 'ସଠିକ୍ ଉତ୍ତର +10 ପଏଣ୍ଟ୍ ଦେଇଥାଏ',
    'dog.got_it': 'ବୁଝିଗଲି! ଖେଳିବା ଆରମ୍ଭ କରନ୍ତୁ',
    'dog.game_over': 'ଖେଳ ଶେଷ! 🐕',
    'dog.final_score': 'ଅନ୍ତିମ ସ୍କୋର୍',
    'dog.play_again': 'ପୁନର୍ବାର ଖେଳନ୍ତୁ',
    'dog.physics_question': '🤔 ଭୌତିକ ବିଜ୍ଞାନ ପ୍ରଶ୍ନ',
    'dog.choose_answer': 'ଦୌଡ଼ିବା ଜାରି ରଖିବା ପାଇଁ ସଠିକ୍ ଉତ୍ତର ବାଛନ୍ତୁ!',
    
    // Gravity Drop Game
    'gravity.title': 'ମାଧ୍ୟାକର୍ଷଣ ଡ୍ରପ୍ ସିମୁଲେସନ୍',
    'gravity.play': 'ଚଲାନ୍ତୁ',
    'gravity.pause': 'ବିରତ',
    'gravity.reset': 'ରିସେଟ୍',
    'gravity.back': 'ଖେଳଗୁଡ଼ିକୁ ଫେରନ୍ତୁ',
    'gravity.description': 'ଦେଖନ୍ତୁ ମାଧ୍ୟାକର୍ଷଣ କିପରି ପଡ଼ୁଥିବା ବସ୍ତୁକୁ ପ୍ରଭାବିତ କରେ! ବଲ୍ 100m ଉଚ୍ଚତାରୁ ଆରମ୍ଭ ହୁଏ।',
    'gravity.height': 'ଉଚ୍ଚତା',
    'gravity.velocity': 'ବେଗ',
    'gravity.time': 'ସମୟ',
    'gravity.concepts': 'ଭୌତିକ ବିଜ୍ଞାନ ଧାରଣା:',
    'gravity.free_fall': 'ମୁକ୍ତ ପତନ: କେବଳ ମାଧ୍ୟାକର୍ଷଣ ଅଧୀନରେ ପଡ଼ୁଥିବା ବସ୍ତୁ',
    'gravity.acceleration': 'ତ୍ୱରଣ: ସ୍ଥିର 9.8 m/s² ତଳକୁ',
    'gravity.equations': 'ସମୀକରଣ: h = h₀ - ½gt², v = gt',
    
    // Common
    'common.loading': 'ଲୋଡ୍ ହେଉଛି...',
    'common.error': 'ତ୍ରୁଟି',
    'common.success': 'ସଫଳତା',
    'common.cancel': 'ବାତିଲ୍ କରନ୍ତୁ',
    'common.save': 'ସେଭ୍ କରନ୍ତୁ',
    'common.edit': 'ସମ୍ପାଦନ କରନ୍ତୁ',
    'common.delete': 'ଡିଲିଟ୍ କରନ୍ତୁ',
    'common.close': 'ବନ୍ଦ କରନ୍ତୁ',
    'common.back': 'ଫେରନ୍ତୁ',
    'common.next': 'ପରବର୍ତ୍ତୀ',
    'common.previous': 'ପୂର୍ବବର୍ତ୍ତୀ',
    'common.finish': 'ଶେଷ କରନ୍ତୁ',
    'common.start': 'ଆରମ୍ଭ କରନ୍ତୁ',
    'common.stop': 'ବିରତ',
    'common.continue': 'ଜାରି ରଖନ୍ତୁ',
    'common.retry': 'ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ',
    
    // Language Switcher
    'lang.english': 'English',
    'lang.hindi': 'हिन्दी',
    'lang.odia': 'ଓଡ଼ିଆ',
    'lang.select': 'ଭାଷା ବାଛନ୍ତୁ',

    // Class Selection
    'class.welcome': 'ଭିଦ୍ୟାଭର୍ସ୍‌କୁ ସ୍ୱାଗତ! 🚀',
    'class.choose': 'ଶିଖିବା ଆରମ୍ଭ କରିବା ପାଇଁ ଆପଣଙ୍କ କ୍ଲାସ୍ ବାଛନ୍ତୁ',
    'class.subtitle': 'AI ସହାୟତା ସହିତ ଇଣ୍ଟାର୍ଆକ୍ଟିଭ୍ ଶିଖଣ',
    'class.progress': 'ପ୍ରଗତି',
    'class.enter': 'କ୍ଲାସ୍ କୁ ପ୍ରବେଶ କରନ୍ତୁ',
    'class.what_get': 'ଆପଣ କ’ଣ ପାଇବେ:',
    'class.ai_tutor': 'AI ଶିକ୍ଷକ',
    'class.mini_games': 'ମିନି ଗେମ୍ସ',
    'class.xp_badges': 'XP ଏବଂ ବ୍ୟାଜ୍',
    'class.progress_tracking': 'ପ୍ରଗତି ଟ୍ରାକିଂ',

    // Subject Dashboard
    'subject.back_classes': 'କ୍ଲାସ୍‌ଗୁଡ଼ିକୁ ଫେରନ୍ତୁ',
    'subject.choose': 'ଶିଖିବା ଜାରି ରଖିବା ପାଇଁ ଏକ ବିଷୟ ବାଛନ୍ତୁ',
    'subject.chapters_completed': 'ଅଧ୍ୟାୟ ସମ୍ପୂର୍ଣ୍ଣ',
    'subject.xp_earned': 'XP ଅର୍ଜିତ',
    'subject.badges': 'ବ୍ୟାଜ୍',
    'subject.progress': 'ପ୍ରଗତି',
    'subject.chapters_available': 'ଉପଲବ୍ଧ ଅଧ୍ୟାୟ',
    'subject.enter': 'ବିଷୟକୁ ପ୍ରବେଶ କରନ୍ତୁ',
    'subject.journey': 'ଆପଣଙ୍କ ଶିଖଣ ଯାତ୍ରା',
    'subject.total_xp': 'ମୋଟ XP',
    'subject.current_level': 'ବର୍ତ୍ତମାନ ଲେଭେଲ୍',
    'subject.streak_days': 'ସ୍ଟ୍ରିକ୍ ଦିନ',
    'subject.badges_earned': 'ଅର୍ଜିତ ବ୍ୟାଜ୍',

    // Chapter View
    'chapter.back_subjects': 'ବିଷୟଗୁଡ଼ିକୁ ଫେରନ୍ତୁ',
    'chapter.back_chapters': 'ଅଧ୍ୟାୟଗୁଡ଼ିକୁ ଫେରନ୍ତୁ',
    'chapter.back_chapter': 'ଅଧ୍ୟାୟକୁ ଫେରନ୍ତୁ',
    'chapter.have_fun': 'ଶିଖିବା ସମୟରେ ମଜା କରନ୍ତୁ!',
    'chapter.study_notes': 'ଅଧ୍ୟୟନ ନୋଟ୍',
    'chapter.completed': 'ସମ୍ପୂର୍ଣ୍ଣ',
    'chapter.quizzes': 'କ୍ୱିଜ୍',
    'chapter.start_quiz': 'କ୍ୱିଜ୍ ଆରମ୍ଭ କରନ୍ତୁ',
    'chapter.mini_games': 'ମିନି ଗେମ୍ସ',
    'chapter.play_game': 'ଗେମ୍ ଖେଳନ୍ତୁ',
    'chapter.did_you_know': 'ଆପଣ ଜାଣନ୍ତି କି? 🤔',
    'chapter.your_progress': 'ଆପଣଙ୍କ ପ୍ରଗତି',
    'chapter.notes_read': 'ପଢ଼ା ନୋଟ୍',
    'chapter.quizzes_completed': 'ସମ୍ପୂର୍ଣ୍ଣ କ୍ୱିଜ୍',
    'chapter.games_played': 'ଖେଳିତ ଗେମ୍ସ',
    'chapter.welcome_to': 'ସ୍ୱାଗତ',
    'chapter.lets_start': 'ଆରମ୍ଭ କରିବା! 🚀',
    'chapter.choose_chapter': 'ଶିଖିବା ଆରମ୍ଭ କରିବା ପାଇଁ ଅଧ୍ୟାୟ ବାଛନ୍ତୁ',
    'chapter.chapter': 'ଅଧ୍ୟାୟ',
    'chapter.level': 'ଲେଭେଲ୍',

    // Lessons Page
    'lessons.title': 'ଇଣ୍ଟର୍ଆକ୍ଟିଭ୍ ଭୌତିକ ବିଜ୍ଞାନ ପାଠ 🎯',
    'lessons.subtitle': 'ହାତକଳ ସହିତ ଏନିମେସନ୍ ଏବଂ ସିମ୍ୟୁଲେସନ୍ ଦ୍ଵାରା ଭୌତିକ ବିଜ୍ଞାନ ଶିଖନ୍ତୁ',
    'lessons.motion_animation': 'ଗତି ଏନିମେସନ୍',
    'lessons.free_fall': 'ମୁକ୍ତ ପତନ ଗତି',
    'lessons.projectile': 'ପ୍ରକ୍ଷେପ୍ୟ ଗତି',
    'lessons.uniform': 'ସମବେଗ ଗତି',
    'lessons.play': 'ଚଲାନ୍ତୁ',
    'lessons.pause': 'ବିରତ',
    'lessons.reset': 'ରିସେଟ୍',
    'lessons.theory': 'ସିଦ୍ଧାନ୍ତ',
    'lessons.key_eq': 'ମୁଖ୍ୟ ସମୀକରଣ:',
    'lessons.mark_complete': '✅ ସମ୍ପୂର୍ଣ୍ଣ ଭାବରେ ଚିହ୍ନିତ କରନ୍ତୁ',
    'lessons.completed_toast': 'ପାଠ ସମ୍ପୂର୍ଣ୍ଣ ହେଲା! ଶାବାଶ!'
    ,
    // Dashboard
    'dashboard.welcome_back': 'ପୁଣି ସ୍ୱାଗତ',
    'dashboard.subtitle': 'ଇଣ୍ଟର୍ଆକ୍ଟିଭ୍ ଶିଖଣ ସହିତ ଆପଣଙ୍କ ଭୌତିକ ଯାତ୍ରା ଜାରି ରଖନ୍ତୁ',
    'dashboard.lessons_completed': 'ସମ୍ପୂର୍ଣ୍ଣ ପାଠ',
    'dashboard.progress': 'ପ୍ରଗତି',
    'dashboard.average_score': 'ମଧ୍ୟମ ସ୍କୋର୍',
    'dashboard.quiz_performance': 'କ୍ୱିଜ୍ ପ୍ରଦର୍ଶନ',
    'dashboard.quizzes_taken': 'ନିଆଯାଇଥିବା କ୍ୱିଜ୍',
    'dashboard.achievements': 'ଉପଲବ୍ଧି',
    'dashboard.quick_actions': 'ତ୍ୱରିତ କାର୍ଯ୍ୟ',
    'dashboard.start_learning': 'ଶିଖିବା ଆରମ୍ଭ କରନ୍ତୁ',
    'dashboard.choose_class_subject': 'ଆପଣଙ୍କ କ୍ଲାସ୍ ଏବଂ ବିଷୟ ବାଛନ୍ତୁ',
    'dashboard.continue_learning': 'ଶିଖିବା ଜାରି ରଖନ୍ତୁ',
    'dashboard.interactive_lessons': 'ଇଣ୍ଟର୍ଆକ୍ଟିଭ୍ ଭୌତିକ ପାଠ',
    'dashboard.take_quiz': 'କ୍ୱିଜ୍ ଦିଅନ୍ତୁ',
    'dashboard.test_knowledge': 'ଆପଣଙ୍କ ଜ୍ଞାନ ପରୀକ୍ଷା କରନ୍ତୁ'
    ,
    // Quiz Page
    'quiz.title': 'ଭୌତିକ କ୍ୱିଜ୍ 🧠',
    'quiz.subtitle': 'ଇଣ୍ଟର୍ଆକ୍ଟିଭ୍ ପ୍ରଶ୍ନମାନଙ୍କ ସହିତ ଜ୍ଞାନ ପରୀକ୍ଷା କରନ୍ତୁ',
    'quiz.question_of': 'ପ୍ରଶ୍ନ',
    'quiz.of': 'ରୁ',
    'quiz.topic': 'ବିଷୟ',
    'quiz.previous': 'ପୂର୍ବବର୍ତ୍ତୀ',
    'quiz.next': 'ପରବର୍ତ୍ତୀ',
    'quiz.submit': 'କ୍ୱିଜ୍ ସମର୍ପଣ କରନ୍ତୁ 🚀',
    'quiz.complete': 'କ୍ୱିଜ୍ ସମାପ୍ତ!',
    'quiz.your_score': 'ଆପଣଙ୍କ ସ୍କୋର୍',
    'quiz.your_answer': 'ଆପଣଙ୍କ ଉତ୍ତର',
    'quiz.correct': 'ସଠିକ୍',
    'quiz.take_another': 'ଅନ୍ୟ ଏକ କ୍ୱିଜ୍ ନିଅନ୍ତୁ',
    'quiz.completed_toast': 'କ୍ୱିଜ୍ ସମାପ୍ତ! ଆପଣ ପାଇଲେ'
    ,
    // Teacher
    'teacher.title': 'ଶିକ୍ଷକ ଡ୍ୟାସବୋର୍ଡ',
    'teacher.welcome': 'ପୁଣି ସ୍ୱାଗତ',
    'teacher.total_students': 'ମୋଟ ଛାତ୍ର',
    'teacher.avg_progress': 'ମଧ୍ୟମ ପ୍ରଗତି',
    'teacher.lessons': 'ପାଠ',
    'teacher.avg_score': 'ମଧ୍ୟମ ସ୍କୋର୍',
    'teacher.assignments': 'ଅସାଇନମେଣ୍ଟ',
    'teacher.active': 'ସକ୍ରିୟ',
    'teacher.recent_activity': 'ସମ୍ପ୍ରତି ଛାତ୍ର କାର୍ଯ୍ୟକଳାପ',
    'teacher.completed_lessons': 'ପାଠ ସମ୍ପୂର୍ଣ୍ଣ',
    'teacher.quick_actions': 'ତ୍ୱରିତ କାର୍ଯ୍ୟ',
    'teacher.create_quiz': 'କ୍ୱିଜ୍ ସୃଷ୍ଟି କରନ୍ତୁ',
    'teacher.view_students': 'ଛାତ୍ରମାନଙ୍କୁ ଦେଖନ୍ତୁ',
    'teacher.attendance': 'ହାଜିରି',
    'teacher.add_by_roll': 'ରୋଲ୍/ନାମଂକନ ଦ୍ଵାରା ଛାତ୍ର ଯୋଡନ୍ତୁ',
    'teacher.enter_roll': 'ରୋଲ୍ ନମ୍ବର ଲେଖନ୍ତୁ',
    'teacher.adding': 'ଯୋଡାଯାଉଛି...',
    'teacher.add_student': 'ଛାତ୍ର ଯୋଡନ୍ତୁ',
    'teacher.toast_not_found': 'ସେହି ରୋଲ୍ ନମ୍ବର ସହିତ କୌଣସି ଛାତ୍ର ମିଳିଲା ନାହିଁ',
    'teacher.toast_added': 'ଛାତ୍ରଙ୍କୁ ଆପଣଙ୍କ ତାଲିକାରେ ଯୋଡାଗଲା',
    'teacher.toast_failed': 'ରୋଲ୍ ନମ୍ବର ଦ୍ଵାରା ଛାତ୍ର ଆଣିବାରେ ବିଫଳ'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['en', 'hi', 'or'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when changed
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

